### ISSUE TITLE
New filename already exists. 

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/wgfilemanager#13]
when I edit and save "Basic directory" I get the error:

Erreur: Exception: New filename already exists. dans le fichier /modules/wgfilemanager/class/DirectoryHandler.php ligne 189

**Comment by ggoffy** [comment]
do not get this error. which new directory name did you use?

**Comment by JJDai54** [comment]
PHP 8.2.13
MySql 8.2.0
![2024-08-23 09 01 44](https://github.com/user-attachments/assets/bc9a8ea4-1766-4318-8742-653b42dde734)
![2024-08-23 09 07 39](https://github.com/user-attachments/assets/9ca71e5a-8c77-4296-b31c-dbee7ece12a0)

**Comment by ggoffy** [comment]
can you please create a screenshot from directory ...\uploads\wgfilemanager\repository

**Comment by JJDai54** [comment]
![2024-08-23 11 29 23](https://github.com/user-attachments/assets/089af4e3-4093-44ed-ba8e-00c72dfdac33)

**Comment by ggoffy** [comment]
hi, found it, should be fixed by https://github.com/XoopsModules25x/wgfilemanager/pull/16

can you please reinstall last version

**Comment by JJDai54** [comment]
ok I don't have the error anymore, but there is still a problem, apparently the name of the folder is not kept
![2024-08-23 13 28 03](https://github.com/user-attachments/assets/da2aed39-9393-4775-b51c-339621cce0c7)

**Comment by JJDai54** [comment]
ok I understood, it's "name" which becomes "full path"
![2024-08-23 15 02 24](https://github.com/user-attachments/assets/d3ec1092-93ad-4ed9-a2b3-8ae3a07000ad)
and then we edit it :
![2024-08-23 15 07 49](https://github.com/user-attachments/assets/ea5e1092-cebd-48b0-923a-d57c20c51ce9)
but it's not very intuitive!

**Comment by ggoffy** [comment]
it became more complicated if the directories are nested
![image](https://github.com/user-attachments/assets/0581b95b-121b-48a9-a9db-f5a99c8af422)
and it is generated autmatically, so you do not have to enter it

**Comment by JJDai54** [comment]
yes but it wasn't very clear since we can modify the field in edition, sorry
